import { useState } from 'react'
import { Gallery } from '../components/mdx/Gallery'
import Lightbox from 'yet-another-react-lightbox'
import Zoom from 'yet-another-react-lightbox/plugins/zoom'
import Thumbnails from 'yet-another-react-lightbox/plugins/thumbnails'
import Slideshow from 'yet-another-react-lightbox/plugins/slideshow'
import Counter from 'yet-another-react-lightbox/plugins/counter'
import 'yet-another-react-lightbox/styles.css'
import 'yet-another-react-lightbox/plugins/thumbnails.css'
import 'yet-another-react-lightbox/plugins/counter.css'

const images = [
  { src: "/til/images/bash/bash-1.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-2.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-3.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-5.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-7.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-9.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-11.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-13.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-15.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-17.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-19.png", alt: "Bash" },
  { src: "/til/images/bash/bash-20.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-22.png", alt: "Bash" },
  { src: "/til/images/bash/bash-24.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-26.png", alt: "Bash" },
  { src: "/til/images/bash/bash-29.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-30.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-33.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-34.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-35.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-36.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-39.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-40.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-41.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-42.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-43.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-44.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-45.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-46.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-47.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-48.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-49.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-50.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-51.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-52.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-53.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-54.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-56.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-58.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-60.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-61.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-62.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-63.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-64.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-65.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-66.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-67.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-68.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-70.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-72.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-74.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-76.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-77.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-78.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-79.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-80.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-81.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-82.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-83.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-84.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-85.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-86.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-87.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-88.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-89.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-90.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-91.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-92.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-93.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-94.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-95.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-96.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-97.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-98.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-100.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-101.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-102.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-103.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-104.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-105.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-106.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-107.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-108.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-109.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-110.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-111.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-112.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-113.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-114.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-115.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-116.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-117.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-118.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-119.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-120.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-121.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-122.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-123.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-124.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-125.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-126.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-127.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-128.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-129.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-130.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-131.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-132.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-133.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-134.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-135.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-136.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-137.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-138.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-139.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-140.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-141.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-142.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-143.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-144.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-145.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-146.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-148.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-149.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-151.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-153.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-155.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-156.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-158.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-160.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-162.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-164.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-166.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-168.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-170.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-172.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-174.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-176.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-178.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-180.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-182.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-184.png", alt: "Bash" },
  { src: "/til/images/bash/bash-186.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-188.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-190.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-192.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-194.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-196.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-198.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-200.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-202.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-204.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-206.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-208.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-212.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-214.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-216.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-218.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-220.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-222.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-224.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-226.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-228.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-230.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-232.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-234.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-236.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-238.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-240.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-242.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-244.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-246.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-248.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-250.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-252.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-254.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-256.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-258.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-260.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-262.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-264.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-266.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-268.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-270.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-272.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-274.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-276.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-278.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-280.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-282.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-284.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-286.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-288.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-290.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-292.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-294.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-296.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-298.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-300.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-301.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-303.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-305.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-307.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-309.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-311.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-313.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-315.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-317.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-319.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-321.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-322.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-323.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-324.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-326.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-327.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-328.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-329.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-330.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-331.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-332.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-334.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-335.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-337.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-338.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-340.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-342.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-344.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-346.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-348.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-350.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-352.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-354.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-356.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-357.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-358.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-360.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-362.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-363.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-364.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-366.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-367.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-369.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-371.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-373.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-375.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-377.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-378.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-379.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-380.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-381.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-382.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-383.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-384.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-385.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-386.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-387.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-388.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-389.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-390.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-391.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-392.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-393.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-394.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-395.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-396.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-397.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-398.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-399.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-400.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-401.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-402.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-403.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-404.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-405.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-406.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-407.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-408.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-409.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-410.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-411.jpg", alt: "Bash" },
  { src: "/til/images/bash/bash-412.jpg", alt: "Bash" }
]

const slides = images.map(img => ({ src: img.src, alt: img.alt }))

export function Bash() {
  const [lightboxIndex, setLightboxIndex] = useState(0)

  return (
    <main className="bash-page">
      <div className="bash-page__hero">
        <h1 className="bash-page__title">Bash 🐾</h1>
        <p className="bash-page__subtitle">
          Good boy. Senior software engineer in training. 280 photos and counting.
        </p>
      </div>
      <Gallery
        images={images}
        showThumbs
        fullBleed
      />
      <Lightbox
        open={lightboxIndex >= 0}
        close={() => setLightboxIndex(-1)}
        index={lightboxIndex}
        slides={slides}
        plugins={[Zoom, Thumbnails, Slideshow, Counter]}
        zoom={{ maxZoomPixelRatio: 4 }}
        carousel={{ finite: false }}
        counter={{ container: { style: { top: 0, bottom: "unset" } } }}
        thumbnails={{ position: "bottom", width: 80, height: 60, gap: 4 }}
        slideshow={{ autoplay: false, delay: 3000 }}
      />
    </main>
  )
}
